# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

Metrics/AbcSize:
  Max: 35

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 100

