sle12_common: &sle12_common
  :dud_dist: "sle12"
  :extra_repos:
    - :server: "http://download.suse.de/ibs/SUSE:/SLE-12-SP1:/GA/standard/"
      :packages: ["grub2-2.02~beta2", "grub2-i386-pc-2.02~beta2", "libzypp", "libsolv-tools", "zypper"]

:sles12:
  <<: *sle12_common
  :yast_url: "http://download.suse.de/ibs/Devel:/YaST:/Head/SLE-12-SP1/"
  :iso_url: "http://dist.suse.de/install/SLE-12-Server-GM/SLE-12-Server-DVD-x86_64-GM-DVD1.iso"

:sles12-sp1:
  <<: *sle12_common
  :yast_url: "http://download.suse.de/ibs/Devel:/YaST:/SLE-12-SP1/SLE-12-SP1/"
  :iso_url: "http://dist.suse.de/install/SLE-12-SP1-Server-GM/SLE-12-SP1-Server-DVD-x86_64-GM-DVD1.iso"

:sles12-sp2:
  <<: *sle12_common
  :yast_url: "http://download.suse.de/ibs/Devel:/YaST:/SLE-12-SP2/SLE_12_SP2/"
# This ISO is used by OpenQA too
  :iso_url: "http://download.suse.de/ibs/SUSE:/SLE-12-SP2:/GA:/Staging:/D/images/iso/Test-Server-DVD-x86_64-Build*-Media.iso"
  :extra_repos:
    - :server: "http://download.suse.de/ibs/Devel:/YaST:/Head/SLE-12-SP2-GA/"
      :packages: ["libsnapper4"]
    - :server: "http://download.suse.de/ibs/SUSE:/SLE-12-SP2:/Update/standard/"
      :packages: ["hwinfo"]

:sles12-sp3:
  :dud_dist: "sle12"
  :yast_url: "http://download.suse.de/ibs/Devel:/YaST:/SLE-12-SP3/SLE_12_SP3_Update/"
# This ISO is used by OpenQA too
  :iso_url: "http://download.suse.de/ibs/SUSE:/SLE-12-SP3:/GA:/Staging:/A/images/iso/Test-Server-DVD-x86_64-Build*-Media.iso"

:caasp1.0:
  :dud_dist: "caasp1.0"
  :dud_method: "instsys"
  :extra_repos: []
  :yast_url:
    - "http://download.suse.de/ibs/Devel:/YaST:/CASP:/1.0/CASP_1.0/"
    - "http://download.suse.de/ibs/Devel:/YaST:/SLE-12-SP2/SLE_12_SP2/"
  :iso_url: "http://dist.suse.de/ibs/SUSE:/SLE-12-SP2:/Update:/Products:/CASP10/images/iso/SUSE-CaaS-Platform-1.0-DVD-x86_64-Build*-Media1.iso"

:leanos15:
  :dud_dist: "sle15"
  :yast_url: "http://download.suse.de/ibs/Devel:/YaST:/Head/SUSE_SLE-15_GA/"
  :iso_url: "http://dist.nue.suse.com/ibs/SUSE:/SLE-15:/GA:/TEST/images/iso/SLE-15-Installer-DVD-x86_64-Build*-Media1.iso"

