packages:
  common:
    - curl
    - gcc
    - gcc-c++
    - libvirt          # Needed to run virtual machines
    - libvirt-devel    # Needed to compile libvirt Vagrant plugin
    - libxml2-devel    # Needed by libvirt plugin from Vagrant
    - libxslt-devel    # Needed by libvirt plugin from Vagrant
    - make
    - ruby-devel
    - virt-install     # Needed to clone QEMU/KVM machines during upgrade
    - virtualbox
  "13.1":
     - kvm                  # Needed to run VMs
     - libvirt-daemon-qemu  # Needed to run QEMU in 13.1
  "13.2":
     - qemu-kvm             # Needed to run VMs
  remote:
    vagrant: https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.rpm
